baseurl = "https://docs.k3cloud.gq"
languageCode = "en-us"
canonifyurls = true
theme = "hello-friend"
paginate = 4
publishDir = "/home/renato/Stuff/dev/github-com/eif0/static-sites/docs-master/_public/"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0

[languages]
  [languages.en]
    title = "k3cloud's docs & stuff"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "more stuff"
    writtenBy = "Posted by"
    readMore = "Read more"
    readOtherPosts = "Other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"

    [languages.en.params.logo]
      logoText = "docs.k3cloud.gq"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "> about"
        url = "/about"
	weight = 20
      [[languages.en.menu.main]]
        identifier = "archieve"
        name = "> archives"
        url = "/archives"
	weight = 40
