name: Pulls repo + build image + push to dockerhub 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    - uses: actions/checkout@v2
    - name: Dotenv Action
      uses: falti/dotenv-action@v0.2.4
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - name: Define variables
      run: |
        cat .env | grep VERSION= | head -n1| grep -o '".*"' | sed 's/"//g' > VERSION1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eif0/k3lab-docs:$(cat VERSION1) --tag eif0/k3lab-docs:latest
    - run: docker push eif0/k3lab-docs
